<a href="https://colab.research.google.com/github/JEBARSON-JESURAJ/AtliQ-Mart-Supplychain/blob/main/AtliQ_Mart.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import packages
import pandas as pd
import numpy as np

In [25]:
#importing data
orders = pd.read_csv('fact_order_lines.csv')
order_agg = pd.read_csv('fact_orders_aggregate.csv')
order_target = pd.read_csv('dim_targets_orders.csv')

In [5]:
orders.head()

,order_id,order_placement_date,customer_id,product_id,order_qty,agreed_delivery_date,actual_delivery_date,delivery_qty,In Full,On Time,On Time In Full
0,FMR34203601,"Tuesday, March 1, 2022",789203,25891601,110,"Friday, March 4, 2022","Friday, March 4, 2022",110,1,1,1
1,FMR32320302,"Tuesday, March 1, 2022",789320,25891203,347,"Wednesday, March 2, 2022","Wednesday, March 2, 2022",347,1,1,1
2,FMR33320501,"Tuesday, March 1, 2022",789320,25891203,187,"Thursday, March 3, 2022","Thursday, March 3, 2022",150,0,1,0
3,FMR34220601,"Tuesday, March 1, 2022",789220,25891203,235,"Friday, March 4, 2022","Friday, March 4, 2022",235,1,1,1
4,FMR33703603,"Tuesday, March 1, 2022",789703,25891203,176,"Thursday, March 3, 2022","Thursday, March 3, 2022",176,1,1,1

In [21]:
order_agg.head()

      order_id  customer_id order_placement_date  on_time  in_full  otif
0  FMR32103503       789103            01-Mar-22        1        0     0
1  FMR34103403       789103            01-Mar-22        1        0     0
2  FMR32103602       789103            01-Mar-22        1        0     0
3  FMR33103602       789103            01-Mar-22        1        0     0
4  FMR33103401       789103            01-Mar-22        1        0     0

In [26]:
order_target.head()

   customer_id  ontime_target%  infull_target%  otif_target%
0       789201              87              81            70
1       789202              85              81            69
2       789203              92              76            70
3       789301              89              78            69
4       789303              88              78            69

In [31]:
#Finding how many Orders we got.

no_of_orders = orders['order_id'].nunique()
no_of_orders

31729

In [14]:
#Finding Total Order Lines.
total_order_lines = orders['order_id'].count()
total_order_lines

In [17]:
#Finding Line Fill Rate
LIFR = sum(orders['In Full']==1) / total_order_lines
LIFR

0.6596083788706739

In [18]:
# Finding Volume Fill Rate
VOFR = sum(orders['delivery_qty']) / sum(orders['order_qty'])
VOFR

0.9659059222446581

In [22]:
#Finding On Time Delivery %
OT = sum(order_agg['on_time'] ==1)/ no_of_orders
OT

0.5903117022282455

In [23]:
#Finding In Full Delivery %
IF = sum(order_agg['in_full'] ==1)/ no_of_orders
IF

0.5278136720350468

In [24]:
#Finding On time & In Full Delivery %
OTIF = sum(order_agg['otif'] ==1)/ no_of_orders
OTIF

0.29020769642913424

In [34]:
from numpy.lib.function_base import average
# Finding Average targets from target_oders

# Average On Time Target
avg_OT_tar = average(order_target['ontime_target%'])
print(avg_OT_tar)
# Average In Full Target
avg_IF_tar = average(order_target['infull_target%'])
print(avg_IF_tar)
# Average On Time In Full Target
avg_OTIF_tar = average(order_target['otif_target%'])
print(avg_OTIF_tar)

86.08571428571429
76.51428571428572
65.91

In [36]:
# Required Metrics

print('1. Total order lines =', total_order_lines)
print('2. Line Fill Rate =', round(LIFR,2))
print('3. Volume fill Rate =', round(VOFR,2))
print('4. No of Orders =', no_of_orders)
print('5. On Time delivery % =', round(OT,2))
print('6. In Full Delivery % =', round(IF,2))
print('7. On Time & In Full Delivery =', round(OTIF,2))
print('8. Average On Time delivery % target = ',round(avg_OT_tar,2))
print('9. Average In Full delivery % target = ',round(avg_IF_tar,2))
print('10. Average On Time & Full Time delivery % target = ',round(avg_OTIF_tar,2))

1. Total order lines = 57096
2. Line Fill Rate = 0.66
3. Volume fill Rate = 0.97
4. No of Orders = 31729
5. On Time delivery % = 0.59
6. In Full Delivery % = 0.53
7. On Time & In Full Delivery = 0.29
8. Average On Time delivery % target =  86.09
9. Average In Full delivery % target =  76.51
10. Average On Time & Full Time delivery % target =  65.91